name: Build and Test

on:
  push:
    branches: [ main, add_build_actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Sync dependencies with uv
      run: uv sync

    - name: Run isort
      run: uv run isort . --check-only --diff

    - name: Run black
      run: uv run black . --check --diff

    - name: Run tests
      run: uv run pytest -v

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build project
      run: uv build